---
- name: Deploy Docker Container

  hosts: all
 
  become: yes

  vars:

    image_name: "ananthak22/calculator:latest"
    container_name: "calculator_container"

  tasks:
    - name: 1. Pull the latest Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: 2. Stop and remove any existing container of the same name
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: 3. Start the container in the background
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        interactive: yes
        tty: yes
        detach: yes

    - name: 4. Open a new GNOME Terminal and attach to the container
      ansible.builtin.command:
        cmd: gnome-terminal -- docker attach {{ container_name }}
      delegate_to: localhost
      become: no
      environment:
        DISPLAY: ":0"

